Mode : 1 #0: Using Slam Map 1: Using predefined Path
WaitTime : 10 # 코드 시작 후 제어 시작까지 기다리는 시간[s]
Speed : 60 # 0~100
Keyboard : 1 # 0: 키보드 콜백 off 1: 키보드 콜백 on

MinX : -3.025559 # Binary GridMap X 오프셋
MinY : -3.457627 # Binary GridMap Y 오프셋

# Way Point 1
GoalX_1 : 4.7
GoalY_1 : 0.0
# Way Point 2
GoalX_2 : 0.0
GoalY_2 : 0.0
# Way Point 3
GoalX_3 : 0.0
GoalY_3 : 0.0
# Way Point 4
GoalX_4 : 0.0
GoalY_4 : 0.0
